name: TypeScript Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: TypeScript Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3.0.11
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: npm Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: TypeScript Build
        uses: alexthemaster/action-build-typescript@v1.3.1
